"""Network mismatch generated by heterogeneous seasonal controllers.

Prospective PAYOFF-B post-freeze extension.

For a shared seasonal error m and actor-specific effective mean phase retention
lambda_i, initially synchronized actors satisfy

    e_i,next = lambda_i m + common innovation.

Across an undirected weighted interaction network, mean squared edge mismatch is

    M_next
      = m^2 / W * sum_{i<j} w_ij (lambda_i-lambda_j)^2
      = m^2 / W * lambda^T L lambda,

where L is the weighted graph Laplacian and W is total undirected edge weight.

The graph identity is standard. Its role here is to connect actor-level
information/control asymmetry to continuous community-level seasonal mismatch.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import isfinite
from typing import Sequence


@dataclass(frozen=True)
class ControllerNetworkMismatch:
    """Weighted controller discordance and induced mismatch."""

    n_actors: int
    total_edge_weight: float
    common_phase_error: float
    controller_dirichlet_energy: float
    normalized_controller_discordance: float
    induced_mean_squared_edge_mismatch: float


def _finite(name: str, value: float) -> float:
    x = float(value)
    if not isfinite(x):
        raise ValueError(f"{name} must be finite")
    return x


def controller_network_mismatch(
    retentions: Sequence[float],
    edges: Sequence[tuple[int, int, float]],
    *,
    common_phase_error: float,
) -> ControllerNetworkMismatch:
    """Return network mismatch induced from an initially synchronized state.

    Parameters
    ----------
    retentions
        Actor-specific effective mean phase-retention coefficients lambda_i.
    edges
        Undirected weighted interactions as (i, j, weight), zero-indexed.
        Weights must be finite and non-negative. Self edges are ignored.
    common_phase_error
        Shared incoming phase error m.

    Returns
    -------
    Weighted Dirichlet energy of the controller field and the resulting
    interaction mismatch energy after one step.
    """

    lam = tuple(_finite("retention", x) for x in retentions)
    if len(lam) < 2:
        raise ValueError("at least two actors are required")
    m = _finite("common_phase_error", common_phase_error)

    total = 0.0
    energy = 0.0
    seen: set[tuple[int, int]] = set()

    for i_raw, j_raw, w_raw in edges:
        i = int(i_raw)
        j = int(j_raw)
        w = _finite("edge weight", w_raw)
        if w < 0.0:
            raise ValueError("edge weights must be non-negative")
        if i == j or w == 0.0:
            continue
        if i < 0 or j < 0 or i >= len(lam) or j >= len(lam):
            raise ValueError("edge endpoint out of bounds")
        a, b = (i, j) if i < j else (j, i)
        if (a, b) in seen:
            raise ValueError("duplicate undirected edge")
        seen.add((a, b))

        total += w
        diff = lam[a] - lam[b]
        energy += w * diff * diff

    if total <= 0.0:
        raise ValueError("positive total edge weight is required")

    discordance = energy / total
    induced = m * m * discordance

    return ControllerNetworkMismatch(
        n_actors=len(lam),
        total_edge_weight=total,
        common_phase_error=m,
        controller_dirichlet_energy=energy,
        normalized_controller_discordance=discordance,
        induced_mean_squared_edge_mismatch=induced,
    )


def complete_graph_controller_variance_identity(
    retentions: Sequence[float],
) -> tuple[float, float]:
    """Return complete-graph discordance and its variance closed form.

    For an unweighted complete graph with N actors,

        (1/W) sum_{i<j}(lambda_i-lambda_j)^2
          = [2N/(N-1)] Var_pop(lambda),

    where Var_pop uses denominator N.
    """

    lam = tuple(_finite("retention", x) for x in retentions)
    n = len(lam)
    if n < 2:
        raise ValueError("at least two actors are required")
    mean = sum(lam) / n
    var_pop = sum((x - mean) ** 2 for x in lam) / n

    edges = [
        (i, j, 1.0)
        for i in range(n)
        for j in range(i + 1, n)
    ]
    result = controller_network_mismatch(
        lam,
        edges,
        common_phase_error=1.0,
    )
    closed = 2.0 * n / (n - 1.0) * var_pop
    return result.normalized_controller_discordance, closed


def binary_controller_cut_identity(
    labels: Sequence[int],
    edges: Sequence[tuple[int, int, float]],
    *,
    retention_0: float,
    retention_1: float,
) -> tuple[float, float]:
    """Return continuous discordance and its binary cut closed form.

    When every actor has one of two retention values, only edges joining
    different controller states contribute. Therefore

        D_lambda
          = (lambda_1-lambda_0)^2 * C/W,

    where C is total crossing-edge weight.

    This is the continuous-controller analogue of the existing PAYOFF-B
    network-cut result for asynchronous cue uptake.
    """

    lab = tuple(int(x) for x in labels)
    if not lab or any(x not in (0, 1) for x in lab):
        raise ValueError("labels must be a non-empty binary sequence")
    lam0 = _finite("retention_0", retention_0)
    lam1 = _finite("retention_1", retention_1)
    ret = [lam1 if x else lam0 for x in lab]

    result = controller_network_mismatch(
        ret,
        edges,
        common_phase_error=1.0,
    )

    total = 0.0
    crossing = 0.0
    seen: set[tuple[int, int]] = set()
    for i_raw, j_raw, w_raw in edges:
        i, j = int(i_raw), int(j_raw)
        w = _finite("edge weight", w_raw)
        if w < 0.0:
            raise ValueError("edge weights must be non-negative")
        if i == j or w == 0.0:
            continue
        if i < 0 or j < 0 or i >= len(lab) or j >= len(lab):
            raise ValueError("edge endpoint out of bounds")
        a, b = (i, j) if i < j else (j, i)
        if (a, b) in seen:
            raise ValueError("duplicate undirected edge")
        seen.add((a, b))
        total += w
        if lab[a] != lab[b]:
            crossing += w

    if total <= 0.0:
        raise ValueError("positive total edge weight is required")

    closed = (lam1 - lam0) ** 2 * crossing / total
    return result.normalized_controller_discordance, closed
