"""Deterministic nonlinear-frequency detection guarantees under bounded error.

This extends PAYOFF's no-refit interior-frequency holdout gate with an ex-ante,
non-probabilistic guarantee. It is deliberately not a statistical power module.

Measurement model
-----------------
For true endpoint margins u and v and a true interior D-minus-S gap y(p), reported
centres satisfy

    |u_hat-u| <= e_u,
    |v_hat-v| <= e_v,
    |y_hat-y| <= e_h.

The validation gate uses the closed bands centre +/- the same declared half-width.
At frequency p the canonical endpoint line is (1-p)u-pv. If the true nonlinear
residual is r(p), then closed-band rejection is guaranteed for every admissible
measurement error exactly when

    |r(p)| > b(p),
    b(p)=2[e_h + (1-p)e_u + p e_v].

Equality is not enough because closed bands may touch.

For an L-Lipschitz residual with r(0)=r(1)=0, a finite design has an exact worst
amplitude that can remain not-guaranteed-detectable. This is the maximum lower
envelope of cones anchored by endpoint zeros and the sample nondetection bounds.
"""
from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction as F
from typing import Sequence

from .frequency_holdout_design import _nonnegative, _positive_int
from .reciprocal_invasion_identification import _q


def _positive(value: object, name: str) -> F:
    x = _q(value)
    if x <= 0:
        raise ValueError(f"{name} must be positive")
    return x


def _points(values: Sequence[object], *, allow_empty: bool = True) -> tuple[F, ...]:
    ps = tuple(_q(p) for p in values)
    if not allow_empty and not ps:
        raise ValueError("at least one holdout frequency is required")
    if any(not F(0) < p < F(1) for p in ps):
        raise ValueError("holdout frequencies must be strictly interior")
    if tuple(sorted(ps)) != ps or len(set(ps)) != len(ps):
        raise ValueError("holdout frequencies must be unique and strictly increasing")
    return ps


def comparison_nondetection_threshold(
    frequency: object,
    *, endpoint_u_error_halfwidth: object,
    endpoint_v_error_halfwidth: object,
    interior_error_halfwidth: object,
) -> F:
    """Exact true-residual magnitude below which rejection is not guaranteed.

    The threshold is twice the sum of the interior measurement half-width and the
    endpoint-derived prediction half-width. The factor two is not a heuristic: one
    copy comes from possible centre displacement and one from closed-band radii.
    """
    p = _q(frequency)
    if not F(0) < p < F(1):
        raise ValueError("frequency must be strictly interior")
    eu = _nonnegative(endpoint_u_error_halfwidth, "endpoint_u_error_halfwidth")
    ev = _nonnegative(endpoint_v_error_halfwidth, "endpoint_v_error_halfwidth")
    eh = _nonnegative(interior_error_halfwidth, "interior_error_halfwidth")
    return 2 * (eh + (1-p)*eu + p*ev)


def worst_undetectable_lipschitz_amplitude(
    frequencies: Sequence[object],
    nondetection_thresholds: Sequence[object],
    *, residual_lipschitz_bound: object,
) -> F:
    """Exact supremum residual amplitude that can evade guaranteed detection.

    Let b_i be each sample's true-residual nondetection threshold. If no sample is
    guaranteed to reject, |r(p_i)| <= b_i. With r(0)=r(1)=0 and Lipschitz constant
    L, every p obeys

        |r(p)| <= min_j [b_j + L |p-p_j|],

    where endpoints are anchors (0,0) and (1,0). The maximum of this lower envelope
    is exact under these sample-bound constraints: the nonnegative envelope itself
    is L-Lipschitz, has zero endpoints, respects all sample bounds, and attains the
    returned ceiling. When b_i are generated by the declared centre-error model,
    one common worst-direction endpoint error plus independent interior errors can
    keep all such nonnegative sample residuals non-rejecting simultaneously.

    Empty frequency input is allowed here and gives the endpoint-only value L/2.
    """
    ps = _points(frequencies)
    bs = tuple(_nonnegative(b, "nondetection_threshold") for b in nondetection_thresholds)
    if len(ps) != len(bs):
        raise ValueError("one nondetection threshold is required per frequency")
    L = _nonnegative(residual_lipschitz_bound, "residual_lipschitz_bound")
    if L == 0:
        return F(0)

    anchors = ((F(0), F(0)),) + tuple(zip(ps, bs)) + ((F(1), F(0)),)

    def envelope(p: F) -> F:
        return min(b + L*abs(p-x) for x, b in anchors)

    candidates = {x for x, _ in anchors}
    # Local maxima of a lower envelope of equal-slope V-cones occur where a
    # +L branch from a left anchor meets a -L branch from a right anchor.
    for i, (xi, bi) in enumerate(anchors):
        for xj, bj in anchors[i+1:]:
            p = (xi+xj)/2 + (bj-bi)/(2*L)
            if xi <= p <= xj:
                candidates.add(p)
    return max(envelope(p) for p in candidates)


@dataclass(frozen=True)
class UniformErrorLipschitzDetectionReceipt:
    holdout_count: int
    residual_lipschitz_bound_exact: str
    endpoint_error_halfwidth_exact: str
    interior_error_halfwidth_exact: str
    sample_nondetection_threshold_exact: str
    recommended_frequencies_exact: tuple[str, ...]
    minimax_undetectable_amplitude_exact: str
    irreducible_detection_floor_exact: str
    holdouts_improve_minimax_guarantee: bool
    design_unique: bool
    guarantee: str = (
        "every_declared_L_lipschitz_residual_with_sup_abs_strictly_above_"
        "minimax_undetectable_amplitude_forces_at_least_one_holdout_rejection"
    )
    statistical_power_computed: bool = False
    probability_model_used: bool = False
    holdout_outcomes_used_for_design: bool = False


def design_uniform_error_lipschitz_detection(
    holdout_count: int,
    *, residual_lipschitz_bound: object,
    endpoint_error_halfwidth: object,
    interior_error_halfwidth: object,
) -> UniformErrorLipschitzDetectionReceipt:
    """Minimax design when both endpoints share one error and holdouts another.

    Put B=2(e_endpoint+e_holdout), the common sample nondetection threshold.
    Endpoints remain exact residual anchors r(0)=r(1)=0.

    If B >= L/2, measurement uncertainty is so large that every interior sample
    cone lies above the endpoint-only envelope. No m-point design improves the
    deterministic worst-case bound L/2; all designs tie.

    If B < L/2, the unique minimax design has boundary gaps larger than interior
    gaps:

        p_i = [i L + (m+1-2i) B] / [(m+1)L],

    and exact worst undetectable amplitude

        U_m = B + (L/2-B)/(m+1).

    Thus nonzero measurement error generally pulls optimal points inward; equal
    spacing is recovered exactly at B=0.
    """
    m = _positive_int(holdout_count, "holdout_count")
    L = _nonnegative(residual_lipschitz_bound, "residual_lipschitz_bound")
    ee = _nonnegative(endpoint_error_halfwidth, "endpoint_error_halfwidth")
    eh = _nonnegative(interior_error_halfwidth, "interior_error_halfwidth")
    B = 2*(ee+eh)

    if L == 0:
        ps = tuple(F(i, m+1) for i in range(1, m+1))
        return UniformErrorLipschitzDetectionReceipt(
            m, "0", str(ee), str(eh), str(B), tuple(map(str, ps)), "0", "0",
            False, False,
        )

    if B >= L/2:
        # Equal spacing is returned only as a neutral reproducible recommendation;
        # it is not uniquely optimal because all strict designs have the same U=L/2.
        ps = tuple(F(i, m+1) for i in range(1, m+1))
        U = L/2
        oracle = worst_undetectable_lipschitz_amplitude(ps, (B,)*m,
            residual_lipschitz_bound=L)
        if oracle != U:
            raise ArithmeticError("noise-dominated design theorem failed oracle check")
        return UniformErrorLipschitzDetectionReceipt(
            m, str(L), str(ee), str(eh), str(B), tuple(map(str, ps)), str(U),
            str(U), False, False,
        )

    denom = (m+1)*L
    ps = tuple((i*L + (m+1-2*i)*B)/denom for i in range(1, m+1))
    U = B + (L/2-B)/(m+1)
    oracle = worst_undetectable_lipschitz_amplitude(ps, (B,)*m,
        residual_lipschitz_bound=L)
    if oracle != U:
        raise ArithmeticError("closed-form minimax design failed exact envelope oracle")
    return UniformErrorLipschitzDetectionReceipt(
        m, str(L), str(ee), str(eh), str(B), tuple(map(str, ps)), str(U), str(B),
        True, True,
    )


@dataclass(frozen=True)
class RequiredHoldoutCountReceipt:
    residual_lipschitz_bound_exact: str
    target_sup_residual_amplitude_exact: str
    sample_nondetection_threshold_exact: str
    required_holdout_count: int | None
    achieved_minimax_undetectable_amplitude_exact: str | None
    status: str
    strict_boundary: bool = True
    statistical_power_computed: bool = False
    sample_size_recommendation: bool = False


def required_holdout_count_for_amplitude(
    target_sup_residual_amplitude: object,
    *, residual_lipschitz_bound: object,
    endpoint_error_halfwidth: object,
    interior_error_halfwidth: object,
) -> RequiredHoldoutCountReceipt:
    """Invert the uniform-error minimax law into a deterministic holdout count.

    The target means alternatives with ||r||_infinity >= A. To guarantee rejection
    for all such alternatives we need U_m < A, strictly, because closed-band contact
    is compatible. This is a deterministic design count, not statistical power or
    replication sample size. The inversion stays O(1) even when the required count
    is extremely large; it does not instantiate the frequency tuple.
    """
    A = _positive(target_sup_residual_amplitude, "target_sup_residual_amplitude")
    L = _nonnegative(residual_lipschitz_bound, "residual_lipschitz_bound")
    ee = _nonnegative(endpoint_error_halfwidth, "endpoint_error_halfwidth")
    eh = _nonnegative(interior_error_halfwidth, "interior_error_halfwidth")
    B = 2*(ee+eh)

    if L == 0 or A > L/2:
        return RequiredHoldoutCountReceipt(
            str(L), str(A), str(B), None, None,
            "target_amplitude_not_attainable_in_declared_endpoint_zero_Lipschitz_class",
        )
    if B >= L/2 or A <= B:
        return RequiredHoldoutCountReceipt(
            str(L), str(A), str(B), None, None,
            "no_finite_holdout_count_can_guarantee_detection_at_declared_error_floor",
        )

    ratio = (L/2-B)/(A-B)
    m = max(1, ratio.numerator // ratio.denominator)
    U = B + (L/2-B)/F(m+1)
    if not U < A:
        raise ArithmeticError("inverted holdout-count formula failed strict guarantee")
    if m > 1:
        previous_U = B + (L/2-B)/F(m)
        if previous_U < A:
            raise ArithmeticError("reported holdout count is not minimal")
    return RequiredHoldoutCountReceipt(
        str(L), str(A), str(B), m, str(U), "finite_deterministic_holdout_count_identified",
    )


@dataclass(frozen=True)
class SignedCurvatureErrorDetectionReceipt:
    curvature_lower_bound_exact: str
    midpoint_guaranteed_departure_exact: str
    midpoint_nondetection_threshold_exact: str
    guaranteed_midpoint_rejection: bool
    critical_curvature_excluded_boundary_exact: str
    statistical_power_computed: bool = False


def signed_curvature_midpoint_detection(
    curvature_lower_bound: object,
    *, endpoint_u_error_halfwidth: object,
    endpoint_v_error_halfwidth: object,
    interior_error_halfwidth: object,
) -> SignedCurvatureErrorDetectionReceipt:
    """Error-aware one-point guarantee for the uniform signed-curvature class.

    The true midpoint departure is at least kappa/8. The midpoint holdout is
    guaranteed to reject iff kappa/8 exceeds its nondetection threshold
    2[e_h+(e_u+e_v)/2]. Equality is an excluded boundary.
    """
    kappa = _nonnegative(curvature_lower_bound, "curvature_lower_bound")
    eu = _nonnegative(endpoint_u_error_halfwidth, "endpoint_u_error_halfwidth")
    ev = _nonnegative(endpoint_v_error_halfwidth, "endpoint_v_error_halfwidth")
    eh = _nonnegative(interior_error_halfwidth, "interior_error_halfwidth")
    Bmid = 2*(eh+(eu+ev)/2)
    departure = kappa/8
    critical = 8*Bmid
    return SignedCurvatureErrorDetectionReceipt(
        str(kappa), str(departure), str(Bmid), departure > Bmid, str(critical),
    )
