"""Pairwise seasonal mismatch generated by asymmetric phase controllers.

Prospective PAYOFF-B post-freeze extension.

The route-wise controller defines an effective mean phase-retention coefficient

    lambda_i = phi_i (1 - G_i A_i g_i K_i)

for actor i under the declared noisy Gaussian feedback representation.

This module asks how differences in those actor-level controllers transform a
shared seasonal error into between-actor mismatch.

The algebra is elementary linear-systems theory. PAYOFF-B should not claim the
matrix identities themselves as generic mathematical novelty. The ecological
contribution is the explicit bridge from readiness/information/control
asymmetry to interaction mismatch.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import isfinite


_TOL = 1e-12


@dataclass(frozen=True)
class PairPhaseStep:
    """One pairwise phase-control step."""

    phase_error_1: float
    phase_error_2: float
    mean_phase_error: float
    interaction_mismatch: float
    lambda_1: float
    lambda_2: float
    mean_retention: float
    retention_difference: float
    innovation_1: float
    innovation_2: float
    next_phase_error_1: float
    next_phase_error_2: float
    next_mean_phase_error: float
    next_interaction_mismatch: float


@dataclass(frozen=True)
class StationaryPairMismatch:
    """Stationary mismatch under constant shared forcing."""

    shared_forcing: float
    lambda_1: float
    lambda_2: float
    stationary_error_1: float
    stationary_error_2: float
    stationary_mismatch: float


def _finite(name: str, value: float) -> float:
    x = float(value)
    if not isfinite(x):
        raise ValueError(f"{name} must be finite")
    return x


def effective_noisy_phase_retention(
    *,
    passive_retention: float,
    control_gain: float,
    information_weight: float,
    readiness_gate: float = 1.0,
    opportunity_gate: float = 1.0,
) -> float:
    """Return regression-scale mean retention for the noisy controller.

    Under the scalar Gaussian phase estimator,

        lambda = phi (1 - G A g K),

    where phi is passive carry-over, G is the physiological/readiness opening
    gate, A is remaining ecological opportunity, g is feedback gain and K is
    the effective checkpoint information weight.
    G=1 recovers the existing decision-controller model; perfect information
    K=1 then gives lambda=phi(1-g).
    """

    phi = _finite("passive_retention", passive_retention)
    g = _finite("control_gain", control_gain)
    k = _finite("information_weight", information_weight)
    gate = _finite("readiness_gate", readiness_gate)
    opportunity = _finite("opportunity_gate", opportunity_gate)
    if g < 0.0:
        raise ValueError("control_gain must be non-negative")
    if not 0.0 <= k <= 1.0:
        raise ValueError("information_weight must lie in [0,1]")
    if not 0.0 <= gate <= 1.0:
        raise ValueError("readiness_gate must lie in [0,1]")
    if not 0.0 <= opportunity <= 1.0:
        raise ValueError("opportunity_gate must lie in [0,1]")
    return phi * (1.0 - gate * opportunity * g * k)


def pairwise_phase_step(
    phase_error_1: float,
    phase_error_2: float,
    *,
    lambda_1: float,
    lambda_2: float,
    innovation_1: float = 0.0,
    innovation_2: float = 0.0,
) -> PairPhaseStep:
    """Propagate mean seasonal error and between-actor mismatch.

    Each actor follows

        e_i,t+1 = lambda_i e_i,t + w_i,t.

    Define common/mean mode

        m_t = (e_1,t + e_2,t)/2

    and interaction mismatch

        Delta_t = e_1,t - e_2,t.

    Then exactly

        m_t+1
          = lambda_bar m_t
            + (delta_lambda/4) Delta_t
            + w_bar,

        Delta_t+1
          = delta_lambda m_t
            + lambda_bar Delta_t
            + delta_w,

    where lambda_bar=(lambda_1+lambda_2)/2 and
    delta_lambda=lambda_1-lambda_2.

    Thus controller asymmetry converts a shared/common seasonal error into
    between-actor mismatch even when the actors were previously synchronized.
    """

    e1 = _finite("phase_error_1", phase_error_1)
    e2 = _finite("phase_error_2", phase_error_2)
    lam1 = _finite("lambda_1", lambda_1)
    lam2 = _finite("lambda_2", lambda_2)
    w1 = _finite("innovation_1", innovation_1)
    w2 = _finite("innovation_2", innovation_2)

    m = 0.5 * (e1 + e2)
    delta = e1 - e2
    lam_bar = 0.5 * (lam1 + lam2)
    dlam = lam1 - lam2

    next1 = lam1 * e1 + w1
    next2 = lam2 * e2 + w2
    next_m = 0.5 * (next1 + next2)
    next_delta = next1 - next2

    # Exact transformed-coordinate identities.
    identity_m = lam_bar * m + 0.25 * dlam * delta + 0.5 * (w1 + w2)
    identity_delta = dlam * m + lam_bar * delta + (w1 - w2)
    if abs(next_m - identity_m) > 1e-10:
        raise AssertionError("mean-mode identity failed")
    if abs(next_delta - identity_delta) > 1e-10:
        raise AssertionError("differential-mode identity failed")

    return PairPhaseStep(
        phase_error_1=e1,
        phase_error_2=e2,
        mean_phase_error=m,
        interaction_mismatch=delta,
        lambda_1=lam1,
        lambda_2=lam2,
        mean_retention=lam_bar,
        retention_difference=dlam,
        innovation_1=w1,
        innovation_2=w2,
        next_phase_error_1=next1,
        next_phase_error_2=next2,
        next_mean_phase_error=next_m,
        next_interaction_mismatch=next_delta,
    )


def mismatch_created_from_shared_error(
    common_phase_error: float,
    *,
    lambda_1: float,
    lambda_2: float,
) -> float:
    """Return one-step mismatch created from an initially synchronized pair.

    If

        e_1=e_2=m
        and
        w_1=w_2,

    then

        Delta_next = (lambda_1-lambda_2) m.

    No initial interaction mismatch is required.
    """

    m = _finite("common_phase_error", common_phase_error)
    lam1 = _finite("lambda_1", lambda_1)
    lam2 = _finite("lambda_2", lambda_2)
    return (lam1 - lam2) * m


def stationary_shared_forcing_mismatch(
    shared_forcing: float,
    *,
    lambda_1: float,
    lambda_2: float,
) -> StationaryPairMismatch:
    """Return persistent mismatch under constant shared forcing.

    For

        e_i,t+1 = lambda_i e_i,t + w,

    and |lambda_i|<1,

        e_i* = w/(1-lambda_i),

    hence

        Delta*
          = w (lambda_1-lambda_2)
            / [(1-lambda_1)(1-lambda_2)].

    A persistent interaction mismatch can therefore exist even when both actors
    experience exactly the same directional seasonal forcing.
    """

    w = _finite("shared_forcing", shared_forcing)
    lam1 = _finite("lambda_1", lambda_1)
    lam2 = _finite("lambda_2", lambda_2)
    if abs(lam1) >= 1.0 or abs(lam2) >= 1.0:
        raise ValueError("stationary mismatch requires |lambda_i| < 1")

    e1 = w / (1.0 - lam1)
    e2 = w / (1.0 - lam2)
    delta = e1 - e2
    closed = w * (lam1 - lam2) / ((1.0 - lam1) * (1.0 - lam2))
    if abs(delta - closed) > 1e-10:
        raise AssertionError("stationary mismatch identity failed")

    return StationaryPairMismatch(
        shared_forcing=w,
        lambda_1=lam1,
        lambda_2=lam2,
        stationary_error_1=e1,
        stationary_error_2=e2,
        stationary_mismatch=delta,
    )


def shared_passive_mismatch_from_information_control(
    common_phase_error: float,
    *,
    passive_retention: float,
    control_gain_1: float,
    information_weight_1: float,
    control_gain_2: float,
    information_weight_2: float,
) -> float:
    """Mismatch generated solely by information/control asymmetry.

    When both actors have the same passive retention phi,

        Delta_next
          = -phi [g_1 K_1 - g_2 K_2] m.

    This cleanly separates controller asymmetry from passive physical
    differences.
    """

    m = _finite("common_phase_error", common_phase_error)
    phi = _finite("passive_retention", passive_retention)
    lam1 = effective_noisy_phase_retention(
        passive_retention=phi,
        control_gain=control_gain_1,
        information_weight=information_weight_1,
    )
    lam2 = effective_noisy_phase_retention(
        passive_retention=phi,
        control_gain=control_gain_2,
        information_weight=information_weight_2,
    )
    return mismatch_created_from_shared_error(
        m,
        lambda_1=lam1,
        lambda_2=lam2,
    )


def shared_passive_mismatch_from_readiness_information_control(
    common_phase_error: float,
    *,
    passive_retention: float,
    readiness_gate_1: float,
    control_gain_1: float,
    information_weight_1: float,
    readiness_gate_2: float,
    control_gain_2: float,
    information_weight_2: float,
    opportunity_gate_1: float = 1.0,
    opportunity_gate_2: float = 1.0,
) -> float:
    """Mismatch from the full two-clock architecture.

    With common passive retention phi,

        lambda_i = phi (1 - G_i A_i g_i K_i),

    so an initially synchronized pair develops

        Delta_next
          = -phi [G_1 g_1 K_1 - G_2 g_2 K_2] m.

    The developmental/physiological layer enters through G_i; remaining
    ecological opportunity enters through A_i; the inferential decision layer
    enters through K_i and g_i.
    """

    m = _finite("common_phase_error", common_phase_error)
    phi = _finite("passive_retention", passive_retention)
    lam1 = effective_noisy_phase_retention(
        passive_retention=phi,
        readiness_gate=readiness_gate_1,
        opportunity_gate=opportunity_gate_1,
        control_gain=control_gain_1,
        information_weight=information_weight_1,
    )
    lam2 = effective_noisy_phase_retention(
        passive_retention=phi,
        readiness_gate=readiness_gate_2,
        opportunity_gate=opportunity_gate_2,
        control_gain=control_gain_2,
        information_weight=information_weight_2,
    )
    return mismatch_created_from_shared_error(
        m,
        lambda_1=lam1,
        lambda_2=lam2,
    )
