"""Identification algebra for clock-portfolio fragility under selection.

Post-freeze PAYOFF-B extension.

A before/after change in population timing variance can be generated by at
least two distinct processes:

1. within-individual response to lost correction opportunity;
2. reweighting/selection of which phenotypes remain observed.

Let E be each individual's counterfactual baseline final phase error and D its
within-individual perturbation-induced change. Let normalized post-perturbation
weights w describe survival/observation/retention in the sample.

Then

    Var_w(E + D) - Var(E)
      = [Var_w(E) - Var(E)]
        + Var_w(D)
        + 2 Cov_w(E, D).

The first bracket is a pure selection/reweighting term. The remaining terms are
the within-individual perturbation contribution in the post-perturbation
weighted population.

This identity is descriptive algebra, not a causal identification theorem.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import isfinite
from typing import Sequence


@dataclass(frozen=True)
class FragilitySelectionDecomposition:
    baseline_variance: float
    selected_baseline_variance: float
    perturbation_variance: float
    baseline_perturbation_covariance: float
    post_variance: float
    observed_variance_change: float
    selection_reweighting_component: float
    within_individual_component: float
    identity_residual: float


def _finite(name: str, value: float) -> float:
    x=float(value)
    if not isfinite(x):
        raise ValueError(f"{name} must be finite")
    return x


def _normalized_weights(weights: Sequence[float], n: int) -> tuple[float,...]:
    if len(weights)!=n:
        raise ValueError("weights must match data length")
    ws=tuple(_finite("weight",w) for w in weights)
    if any(w<0 for w in ws):
        raise ValueError("weights must be non-negative")
    total=sum(ws)
    if total<=0:
        raise ValueError("positive total weight is required")
    return tuple(w/total for w in ws)


def weighted_mean(values: Sequence[float], weights: Sequence[float]) -> float:
    xs=tuple(_finite("value",x) for x in values)
    ws=_normalized_weights(weights,len(xs))
    return sum(w*x for w,x in zip(ws,xs))


def weighted_variance(values: Sequence[float], weights: Sequence[float]) -> float:
    xs=tuple(_finite("value",x) for x in values)
    ws=_normalized_weights(weights,len(xs))
    m=sum(w*x for w,x in zip(ws,xs))
    return sum(w*(x-m)**2 for w,x in zip(ws,xs))


def weighted_covariance(
    x: Sequence[float],
    y: Sequence[float],
    weights: Sequence[float],
) -> float:
    xs=tuple(_finite("x",v) for v in x)
    ys=tuple(_finite("y",v) for v in y)
    if len(xs)!=len(ys):
        raise ValueError("x and y must have equal length")
    ws=_normalized_weights(weights,len(xs))
    mx=sum(w*v for w,v in zip(ws,xs))
    my=sum(w*v for w,v in zip(ws,ys))
    return sum(w*(a-mx)*(b-my) for w,a,b in zip(ws,xs,ys))


def population_variance(values: Sequence[float]) -> float:
    xs=tuple(_finite("value",x) for x in values)
    if not xs:
        raise ValueError("at least one value is required")
    m=sum(xs)/len(xs)
    return sum((x-m)**2 for x in xs)/len(xs)


def decompose_variance_change(
    baseline_error: Sequence[float],
    individual_shift: Sequence[float],
    post_weights: Sequence[float],
) -> FragilitySelectionDecomposition:
    """Decompose observed population variance change exactly.

    baseline_error:
        Individual counterfactual pre-perturbation final phase errors E.

    individual_shift:
        Within-individual perturbation-induced changes D, so post error is E+D.

    post_weights:
        Relative post-perturbation observation/survival weights.

    The identity is

        Var_w(E+D)-Var(E)
          = [Var_w(E)-Var(E)]
            + Var_w(D)
            + 2 Cov_w(E,D).
    """

    e=tuple(_finite("baseline_error",x) for x in baseline_error)
    d=tuple(_finite("individual_shift",x) for x in individual_shift)
    if len(e)!=len(d):
        raise ValueError("baseline_error and individual_shift must match")
    if not e:
        raise ValueError("at least one individual is required")
    w=_normalized_weights(post_weights,len(e))

    baseline=population_variance(e)
    selected_baseline=weighted_variance(e,w)
    shift_var=weighted_variance(d,w)
    cov=weighted_covariance(e,d,w)
    post=weighted_variance([a+b for a,b in zip(e,d)],w)

    selection=selected_baseline-baseline
    within=shift_var+2.0*cov
    change=post-baseline
    residual=change-selection-within

    return FragilitySelectionDecomposition(
        baseline_variance=baseline,
        selected_baseline_variance=selected_baseline,
        perturbation_variance=shift_var,
        baseline_perturbation_covariance=cov,
        post_variance=post,
        observed_variance_change=change,
        selection_reweighting_component=selection,
        within_individual_component=within,
        identity_residual=residual,
    )
