"""Transient mismatch generated by asynchronous readiness gates."""

from __future__ import annotations
from dataclasses import dataclass
from math import exp, isfinite

@dataclass(frozen=True)
class ReadinessWindowResult:
    common_initial_error: float
    correction_rate: float
    readiness_time_1: float
    readiness_time_2: float
    window_duration: float
    earlier_actor: int
    mismatch_at_late_readiness: float
    max_abs_mismatch: float

def _finite(name: str, value: float) -> float:
    x=float(value)
    if not isfinite(x):
        raise ValueError(f"{name} must be finite")
    return x

def _nonnegative(name: str, value: float) -> float:
    x=_finite(name,value)
    if x < 0:
        raise ValueError(f"{name} must be non-negative")
    return x

def phase_error_after_readiness(
    initial_error: float,
    time: float,
    *,
    readiness_time: float,
    correction_rate: float,
) -> float:
    """Before readiness error is retained; after readiness it decays."""
    e0=_finite("initial_error",initial_error)
    t=_finite("time",time)
    tau=_finite("readiness_time",readiness_time)
    c=_nonnegative("correction_rate",correction_rate)
    if t < tau:
        return e0
    return e0*exp(-c*(t-tau))

def pairwise_readiness_mismatch(
    initial_error: float,
    time: float,
    *,
    readiness_time_1: float,
    readiness_time_2: float,
    correction_rate: float,
) -> float:
    """Return signed mismatch e1(t)-e2(t)."""
    return (
        phase_error_after_readiness(
            initial_error,time,
            readiness_time=readiness_time_1,
            correction_rate=correction_rate,
        )
        -
        phase_error_after_readiness(
            initial_error,time,
            readiness_time=readiness_time_2,
            correction_rate=correction_rate,
        )
    )

def readiness_window_peak(
    initial_error: float,
    *,
    readiness_time_1: float,
    readiness_time_2: float,
    correction_rate: float,
) -> ReadinessWindowResult:
    """Exact maximum mismatch from different readiness times.

    If tau_1 <= tau_2 and both actors have the same correction rate c after
    readiness,

        |Delta_max| = |e0| [1-exp(-c Delta_tau)]

    and the peak occurs at the later readiness time.
    """
    e0=_finite("initial_error",initial_error)
    tau1=_finite("readiness_time_1",readiness_time_1)
    tau2=_finite("readiness_time_2",readiness_time_2)
    c=_nonnegative("correction_rate",correction_rate)
    if tau1 <= tau2:
        early_actor,early,late=1,tau1,tau2
    else:
        early_actor,early,late=2,tau2,tau1
    width=late-early
    peak=abs(e0)*(1-exp(-c*width))
    mismatch=pairwise_readiness_mismatch(
        e0,late,
        readiness_time_1=tau1,
        readiness_time_2=tau2,
        correction_rate=c,
    )
    return ReadinessWindowResult(
        common_initial_error=e0,
        correction_rate=c,
        readiness_time_1=tau1,
        readiness_time_2=tau2,
        window_duration=width,
        earlier_actor=early_actor,
        mismatch_at_late_readiness=mismatch,
        max_abs_mismatch=peak,
    )

def readiness_window_marginal_effect(
    initial_error: float,
    window_duration: float,
    *,
    correction_rate: float,
) -> float:
    """d|Delta_max|/d Delta_tau = |e0| c exp(-c Delta_tau)."""
    e0=_finite("initial_error",initial_error)
    width=_nonnegative("window_duration",window_duration)
    c=_nonnegative("correction_rate",correction_rate)
    return abs(e0)*c*exp(-c*width)
