"""Serial two-clock decomposition for seasonal mismatch.

Post-freeze PAYOFF-B theory.

Clock 1 (developmental / physiological readiness) determines the phase state
at entry into the focal behavioral mode.  Clock 2 (information-dependent
decision control) determines how that initial error is propagated and corrected
after entry.

For actor i after entry,

    e_i,k+1 = lambda_i e_i,k

in the simplest no-innovation representation.

Writing initial common error and interaction mismatch as

    m_0 = (e_1,0 + e_2,0)/2
    Delta_0 = e_1,0 - e_2,0,

the exact mismatch after n checkpoints is

    Delta_n =
        (lambda_1^n - lambda_2^n) m_0
        + 0.5 (lambda_1^n + lambda_2^n) Delta_0.

The first term is mismatch generated by controller asymmetry from shared error.
The second is propagation of mismatch already created by the readiness/entry
clocks.

This is elementary linear-systems algebra.  The ecological contribution is the
serial decomposition of two distinct seasonal clock mechanisms.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import isfinite


@dataclass(frozen=True)
class SerialMismatchDecomposition:
    steps: int
    lambda_1: float
    lambda_2: float
    initial_mean_error: float
    initial_mismatch: float
    controller_generated_component: float
    timer_propagated_component: float
    final_mismatch: float
    final_error_1: float
    final_error_2: float


@dataclass(frozen=True)
class PostEntryController:
    passive_retention: float
    opportunity_gate: float
    information_weight: float
    decision_gain: float
    effective_post_entry_gain: float
    phase_retention: float


def _finite(name: str, value: float) -> float:
    x=float(value)
    if not isfinite(x):
        raise ValueError(f"{name} must be finite")
    return x


def _unit(name: str, value: float) -> float:
    x=_finite(name,value)
    if x < 0.0 or x > 1.0:
        raise ValueError(f"{name} must lie in [0,1]")
    return x


def _nonnegative(name: str, value: float) -> float:
    x=_finite(name,value)
    if x < 0.0:
        raise ValueError(f"{name} must be non-negative")
    return x


def post_entry_phase_retention(
    *,
    passive_retention: float,
    opportunity_gate: float,
    information_weight: float,
    decision_gain: float,
) -> PostEntryController:
    """Return post-entry phase retention for the serial architecture.

    Readiness is not multiplied into the downstream controller once the focal
    behavioral mode has been entered.  The physiological clock determines the
    entry state; after entry,

        h = O g
        lambda = phi (1 - O g K).

    A concurrent readiness gate can still be added in systems where it is
    independently measured, but it is not assumed by default.
    """

    phi=_finite("passive_retention",passive_retention)
    O=_unit("opportunity_gate",opportunity_gate)
    K=_unit("information_weight",information_weight)
    g=_nonnegative("decision_gain",decision_gain)
    h=O*g
    lam=phi*(1.0-h*K)
    return PostEntryController(
        passive_retention=phi,
        opportunity_gate=O,
        information_weight=K,
        decision_gain=g,
        effective_post_entry_gain=h,
        phase_retention=lam,
    )


def serial_mismatch_decomposition(
    *,
    initial_mean_error: float,
    initial_mismatch: float,
    lambda_1: float,
    lambda_2: float,
    steps: int,
) -> SerialMismatchDecomposition:
    """Decompose later mismatch into timer and controller components exactly."""

    m0=_finite("initial_mean_error",initial_mean_error)
    d0=_finite("initial_mismatch",initial_mismatch)
    l1=_finite("lambda_1",lambda_1)
    l2=_finite("lambda_2",lambda_2)
    n=int(steps)
    if n < 0:
        raise ValueError("steps must be non-negative")

    e10=m0+0.5*d0
    e20=m0-0.5*d0
    p1=l1**n
    p2=l2**n
    e1=p1*e10
    e2=p2*e20

    controller=(p1-p2)*m0
    timer=0.5*(p1+p2)*d0
    delta=e1-e2

    if abs(delta-(controller+timer)) > 1e-10:
        raise AssertionError("serial two-clock identity failed")

    return SerialMismatchDecomposition(
        steps=n,
        lambda_1=l1,
        lambda_2=l2,
        initial_mean_error=m0,
        initial_mismatch=d0,
        controller_generated_component=controller,
        timer_propagated_component=timer,
        final_mismatch=delta,
        final_error_1=e1,
        final_error_2=e2,
    )


def common_controller_timer_decay(
    initial_mismatch: float,
    *,
    phase_retention: float,
    steps: int,
) -> float:
    """Mismatch remaining when actors share the same downstream controller."""

    d0=_finite("initial_mismatch",initial_mismatch)
    lam=_finite("phase_retention",phase_retention)
    n=int(steps)
    if n<0:
        raise ValueError("steps must be non-negative")
    return lam**n*d0


def controller_generated_mismatch(
    common_initial_error: float,
    *,
    lambda_1: float,
    lambda_2: float,
    steps: int,
) -> float:
    """Mismatch generated after synchronized entry by controller asymmetry."""

    m0=_finite("common_initial_error",common_initial_error)
    l1=_finite("lambda_1",lambda_1)
    l2=_finite("lambda_2",lambda_2)
    n=int(steps)
    if n<0:
        raise ValueError("steps must be non-negative")
    return (l1**n-l2**n)*m0


def final_phase_variance_no_innovation(
    initial_variance: float,
    *,
    phase_retention: float,
    steps: int,
) -> float:
    """Return final phase variance under a homogeneous serial controller.

    With no new process innovation,

        Var(e_n) = lambda^(2n) Var(e_0).

    This makes timer precision and downstream correction partially substitutable
    for final tracking precision.
    """

    v0=_nonnegative("initial_variance",initial_variance)
    lam=_finite("phase_retention",phase_retention)
    n=int(steps)
    if n<0:
        raise ValueError("steps must be non-negative")
    return lam**(2*n)*v0


def required_initial_variance_for_target(
    target_final_variance: float,
    *,
    phase_retention: float,
    steps: int,
) -> float:
    """Return entry-timer variance compatible with a target final variance.

    For nonzero lambda,

        V0 = V_target / lambda^(2n).

    A strong downstream controller (small |lambda|) permits a much noisier
    entry timer while achieving the same final precision.
    """

    vt=_nonnegative("target_final_variance",target_final_variance)
    lam=_finite("phase_retention",phase_retention)
    n=int(steps)
    if n<0:
        raise ValueError("steps must be non-negative")
    factor=lam**(2*n)
    if factor==0.0:
        if vt==0.0:
            return 0.0
        raise ValueError("positive target variance is incompatible with zero retention under the no-innovation model")
    return vt/factor
